
import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/contexts/AppContext";


export const metadata: Metadata = {
  title: "Nimucure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AppProvider>  {children}</AppProvider>
      
      </body>
    </html>
  );
}